controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.index:
    path:          /
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'index.html.twig'
